-- MySQL Script generated by MySQL Workbench
-- Mon 04 Oct 2021 09:56:01 PM -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agentdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agentdb` ;

-- -----------------------------------------------------
-- Schema agentdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agentdb` ;
USE `agentdb` ;

-- -----------------------------------------------------
-- Table `agentdb`.`chain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agentdb`.`chain` ;

CREATE TABLE IF NOT EXISTS `agentdb`.`chain` (
  `chainid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `chainname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`chainid`),
  UNIQUE INDEX `idchain_UNIQUE` (`chainid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agentdb`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agentdb`.`city` ;

CREATE TABLE IF NOT EXISTS `agentdb`.`city` (
  `cityid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cityname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cityid`),
  UNIQUE INDEX `idchain_UNIQUE` (`cityid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agentdb`.`pos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agentdb`.`pos` ;

CREATE TABLE IF NOT EXISTS `agentdb`.`pos` (
  `posid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `poschainid` INT UNSIGNED NOT NULL,
  `poscityid` INT UNSIGNED NOT NULL,
  `posaddress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`posid`),
  UNIQUE INDEX `idpos_UNIQUE` (`posid` ASC) VISIBLE,
  INDEX `fk_pos_chain_idx` (`poschainid` ASC) VISIBLE,
  INDEX `fk_pos_city1_idx` (`poscityid` ASC) VISIBLE,
  CONSTRAINT `fk_pos_chain`
    FOREIGN KEY (`poschainid`)
    REFERENCES `agentdb`.`chain` (`chainid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pos_city1`
    FOREIGN KEY (`poscityid`)
    REFERENCES `agentdb`.`city` (`cityid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agentdb`.`personal_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agentdb`.`personal_info` ;

CREATE TABLE IF NOT EXISTS `agentdb`.`personal_info` (
  `infoid` INT UNSIGNED NOT NULL,
  `infoname` VARCHAR(45) NOT NULL,
  `infophone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`infoid`),
  UNIQUE INDEX `id_UNIQUE` (`infoid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agentdb`.`agent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agentdb`.`agent` ;

CREATE TABLE IF NOT EXISTS `agentdb`.`agent` (
  `agentposid` INT UNSIGNED NOT NULL,
  `agentinfoid` INT UNSIGNED NOT NULL,
  INDEX `fk_promoter_pos1_idx` (`agentposid` ASC) VISIBLE,
  PRIMARY KEY (`agentinfoid`),
  CONSTRAINT `fk_promoter_pos1`
    FOREIGN KEY (`agentposid`)
    REFERENCES `agentdb`.`pos` (`posid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promoter_personal_info1`
    FOREIGN KEY (`agentinfoid`)
    REFERENCES `agentdb`.`personal_info` (`infoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agentdb`.`trainer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agentdb`.`trainer` ;

CREATE TABLE IF NOT EXISTS `agentdb`.`trainer` (
  `trainerinfoid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`trainerinfoid`),
  CONSTRAINT `fk_trainer_personal_info1`
    FOREIGN KEY (`trainerinfoid`)
    REFERENCES `agentdb`.`personal_info` (`infoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agentdb`.`topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agentdb`.`topic` ;

CREATE TABLE IF NOT EXISTS `agentdb`.`topic` (
  `topicid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `topicname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`topicid`),
  UNIQUE INDEX `idsubject_UNIQUE` (`topicid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agentdb`.`training`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agentdb`.`training` ;

CREATE TABLE IF NOT EXISTS `agentdb`.`training` (
  `trainingid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trainingagentinfoid` INT UNSIGNED NOT NULL,
  `trainingtrainerinfoid` INT UNSIGNED NOT NULL,
  `trainingdate` DATE NOT NULL,
  `trainingtopicid` INT UNSIGNED NOT NULL,
  `traininggrade` INT NOT NULL,
  PRIMARY KEY (`trainingid`),
  UNIQUE INDEX `idcapacitation_UNIQUE` (`trainingid` ASC) VISIBLE,
  INDEX `fk_capacitation_promoter1_idx` (`trainingagentinfoid` ASC) VISIBLE,
  INDEX `fk_capacitation_trainer1_idx` (`trainingtrainerinfoid` ASC) VISIBLE,
  INDEX `fk_capacitation_subject1_idx` (`trainingtopicid` ASC) VISIBLE,
  CONSTRAINT `fk_capacitation_promoter1`
    FOREIGN KEY (`trainingagentinfoid`)
    REFERENCES `agentdb`.`agent` (`agentinfoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_capacitation_trainer1`
    FOREIGN KEY (`trainingtrainerinfoid`)
    REFERENCES `agentdb`.`trainer` (`trainerinfoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_capacitation_subject1`
    FOREIGN KEY (`trainingtopicid`)
    REFERENCES `agentdb`.`topic` (`topicid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agentdb`.`supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agentdb`.`supervisor` ;

CREATE TABLE IF NOT EXISTS `agentdb`.`supervisor` (
  `supervisorinfoid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`supervisorinfoid`),
  CONSTRAINT `fk_supervisor_personal_info1`
    FOREIGN KEY (`supervisorinfoid`)
    REFERENCES `agentdb`.`personal_info` (`infoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agentdb`.`evaluation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agentdb`.`evaluation` ;

CREATE TABLE IF NOT EXISTS `agentdb`.`evaluation` (
  `evaluationid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `evaluationsupervisorinfoid` INT UNSIGNED NOT NULL,
  `evaluationagentinfoid` INT UNSIGNED NOT NULL,
  `evaluationdate` DATE NOT NULL,
  `evaluationcomments` TEXT NULL,
  PRIMARY KEY (`evaluationid`),
  INDEX `fk_evaluation_supervisor1_idx` (`evaluationsupervisorinfoid` ASC) VISIBLE,
  INDEX `fk_evaluation_promoter1_idx` (`evaluationagentinfoid` ASC) VISIBLE,
  CONSTRAINT `fk_evaluation_supervisor1`
    FOREIGN KEY (`evaluationsupervisorinfoid`)
    REFERENCES `agentdb`.`supervisor` (`supervisorinfoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluation_promoter1`
    FOREIGN KEY (`evaluationagentinfoid`)
    REFERENCES `agentdb`.`agent` (`agentinfoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agentdb`.`trainer_has_topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agentdb`.`trainer_has_topic` ;

CREATE TABLE IF NOT EXISTS `agentdb`.`trainer_has_topic` (
  `trainerinfoid` INT UNSIGNED NOT NULL,
  `topicid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`trainerinfoid`, `topicid`),
  INDEX `fk_trainer_has_subject_subject1_idx` (`topicid` ASC) VISIBLE,
  INDEX `fk_trainer_has_subject_trainer1_idx` (`trainerinfoid` ASC) VISIBLE,
  CONSTRAINT `fk_trainer_has_subject_trainer1`
    FOREIGN KEY (`trainerinfoid`)
    REFERENCES `agentdb`.`trainer` (`trainerinfoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainer_has_subject_subject1`
    FOREIGN KEY (`topicid`)
    REFERENCES `agentdb`.`topic` (`topicid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
